---
title: "4-northeast-analysis"
author: "Daniel Hocking"
date: "August 28, 2014"
output: html_document
---

```{r results = 'hide', }
#rm(list=ls())

library(knitr)
#basename <- gsub(".Rmd", "", knitr:::knit_concord$get("infile"))
#opts_chunk$set(fig.path = paste("figure/", basename, "-", sep = ""), cache.path = paste("cache/", basename, "/", sep = ""))
#basename <- "testName"
#opts_chunk$set(cache.path = paste("cache/", basename, "/", sep = ""))
#opts_chunk$set(cache = 1)
opts_chunk$set(tidy = FALSE, warning = FALSE, message = FALSE, comment = NA, verbose = TRUE)

```


```{r results = 'hide', warning=FALSE, message=FALSE}
library(ggplot2)
library(ggmcmc)
library(dplyr)
library(nlme)
library(devtools)
install_github("Conte-Ecology/conteStreamTemperature")
library(conteStreamTemperature)

#setwd('/Users/Dan/Documents/Research/Stream_Climate_Change/temperatureProject/')
#setwd('C:/Users/dhocking/Documents/temperatureProject/')

#baseDir <- 'C:/KPONEIL/GitHub/projects/temperatureProject/'
#baseDir <- "/Users/Dan/Documents/Research/Stream_Climate_Change/conteStreamTemperature_northeast"
baseDir <- getwd() # works as long as you have the project loaded in RStudio - does not work for kniting

dataInDir <- paste0(baseDir, '/dataIn/')
dataOutDir <- paste0(baseDir, '/dataOut/')
dataLocalDir <- paste0(baseDir, '/localData/')
graphsDir <- paste0(baseDir, '/graphs/')

#source(paste0(baseDir, 'code/functions/temperatureModelingFunctions.R'))

# load standardized and formatted data created with the 3-statModelPrep.Rmd script
load(paste0(dataOutDir, 'tempDataSync.RData'))
```

```{r eval = FALSE}
print(getwd())
```


```{r run-model, results = 'hide'}
########## JAGS Model ##############
coda.tf <- T # currently only works in full for TRUE (using coda.samples)
M3 <- modelRegionalTemp(tempDataSyncS, n.burn = 1000, n.it = 1000, n.thin = 1, n.chains = 3, coda = coda.tf, param.list = c("sigma",
            "B.0",
            #"B.site",
            #"rho.B.site",
            "mu.site",
            "sigma.b.site",
            #"B.huc",
            #"rho.B.huc",
            #"B.year",
            #"rho.B.year",
            "mu.year",
            "sigma.b.year"))

save(M3, file = paste0(dataLocalDir, "northeast-mcmc.RData"))

pdf("test.pdf")
plot(M3)
dev.off()
```

```{r test site within HUC model with residual AR1}
######
# rename all variables before setting the fixed and random, then select them by list
####

## Change to use model matrix for simplicity and consistency
data.fixed <- data.frame(intercept = 1,
                    lat = tempDataSyncS$Latitude,
                    lon = tempDataSyncS$Longitude,
                    drainage = tempDataSyncS$TotDASqKM,
                    forest = tempDataSyncS$Forest,
                    elevation = tempDataSyncS$ReachElevationM,
                    coarseness = tempDataSyncS$SurficialCoarseC,
                    wetland = tempDataSyncS$CONUSWetland,
                    impoundments = tempDataSyncS$ImpoundmentsAllSqKM,
                    airT.drainage = tempDataSyncS$airTemp * tempDataSyncS$TotDASqKM)

data.random.sites <- data.frame(intercept.site = 1, 
                     airTemp = tempDataSyncS$airTemp, 
                     #airTempLag1 = tempDataSyncS$airTempLagged1,
                     airTempLag2 = tempDataSyncS$airTempLagged2,
                     precip = tempDataSyncS$prcp,
                     precipLag1 = tempDataSyncS$prcpLagged1,
                     #precipLag2 = tempDataSyncS$prcpLagged2,
                    # effect of interaction with random and fixed effects?
                     airT.precip = tempDataSyncS$airTemp * tempDataSyncS$prcp) # airT.precip2 = tempDataSyncS$airTemp * tempDataSyncS$prcpLagged1 - doesn't converge

data.random.years <- data.frame(intercept.year = 1, 
                     dOY = tempDataSyncS$dOY, 
                     dOY2 = tempDataSyncS$dOY^2,
                     dOY3 = tempDataSyncS$dOY^3)

monitor.params <- c("residuals",
            "deviance",
            "sigma",
            "B.ar1",
            #"mu.ar1",
            #"sigma.ar1",
            "B.0",
            "B.site",
            "rho.B.site",
            "mu.site",
            "sigma.b.site",
            "B.huc",
            "rho.B.huc",
            "mu.huc",
            "sigma.b.huc",
            "B.year",
            "rho.B.year",
            "mu.year",
            "sigma.b.year")

coda.tf <- T # currently only works in full for TRUE (using coda.samples)
system.time(M.ar1 <- modelRegionalTempAR1(tempDataSyncS, data.fixed=data.fixed, data.random.sites=data.random.sites, data.random.years=data.random.years, firstObsRows = firstObsRows, evalRows = evalRows, n.burn = 1000, n.it = 1000, n.thin = 1, nc = 3, coda = coda.tf, param.list = monitor.params)) # Slow with AR1: ~3-6 min per 100 iterations (13 min per 100 iter for site AR)

save(M.ar1, file = paste0(dataLocalDir, "northeast-mcmc.RData"))

#pdf("test-huc.pdf")
#plot(M.huc)
#dev.off()
```

## Evaluate MCMC Iterations
```{r check model convergence and mixing}
#ggs.ar1 <- ggs(M.ar1) # slow and memory intensive

#ggmcmc(ggs.ar1, file = "ggmcmc-ar1.pdf", family = "mu.huc", plot = c("ggs_density",  "ggs_traceplot", "ggs_running", "ggs_compare_partial", "ggs_autocorrelation", "ggs_crosscorrelation", "ggs_Rhat", "ggs_geweke", "ggs_caterpillar"))
#dev.off()

ggs.ar1.B.0 <- ggs(M.ar1, family = "B.0")
ggs_traceplot(ggs.ar1.B.0, family = "B.0")

ggs.ar1.mu.huc <- ggs(M.ar1, family = "mu.huc")
ggs_traceplot(ggs.ar1.mu.huc, family = "mu.huc")

ggs.ar1.mu.year <- ggs(M.ar1, family = "mu.year")
ggs_traceplot(ggs.ar1.mu.year, family = "mu.year")

ggs.ar1.mu.ar1 <- ggs(M.ar1, family = "mu.ar1")
ggs_traceplot(ggs.ar1.mu.ar1, family = "mu.ar1")

ggs.ar1.sigma.ar1 <- ggs(M.ar1, family = "sigma.ar1")
ggs_traceplot(ggs.ar1.sigma.ar1, family = "sigma.ar1")

ggs.ar1.sigma.b.site <- ggs(M.ar1, family = "sigma.b.site")
ggs_traceplot(ggs.ar1.sigma.b.site, family = "sigma.b.site")

ggs.ar1.sigma.b.huc <- ggs(M.ar1, family = "sigma.b.huc")
ggs_traceplot(ggs.ar1.sigma.b.huc, family = "sigma.b.huc")

ggs.ar1.sigma.b.year <- ggs(M.ar1, family = "sigma.b.year")
ggs_traceplot(ggs.ar1.sigma.b.year, family = "sigma.b.year")

ggs.ar1.rho.huc <- ggs(M.ar1, family = "rho.B.huc")
ggmcmc(ggs.ar1.rho.huc, file = 'localData/ggmcmc-ar1-rho-huc.pdf', family = "rho.B.huc", plot = "ggs_traceplot")

ggs.ar1.B.ar1 <- ggs(M.ar1, family = "B.ar1")
ggmcmc(ggs.ar1.B.ar1, file = 'localData/ggmcmc-ar1-B-ar1.pdf', family = "B.ar1", plot = c("ggs_traceplot", "ggs_compare_partial", "ggs_autocorrelation"))

```




```{r test site within HUC model}
######
# rename all variables before setting the fixed and random, then select them by list
####
data.fixed <- data.frame(intercept = 1,
                    lat = tempDataSyncS$Latitude,
                    lon = tempDataSyncS$Longitude,
                    drainage = tempDataSyncS$TotDASqKM,
                    forest = tempDataSyncS$Forest,
                    elevation = tempDataSyncS$ReachElevationM,
                    coarseness = tempDataSyncS$SurficialCoarseC,
                    wetland = tempDataSyncS$CONUSWetland,
                    impoundments = tempDataSyncS$ImpoundmentsAllSqKM)

data.random.sites <- data.frame(intercept.site = 1, 
                     airTemp = tempDataSyncS$airTemp, 
                     #airTempLag1 = tempDataSyncS$airTempLagged1,
                     airTempLag2 = tempDataSyncS$airTempLagged2,
                     precip = tempDataSyncS$prcp,
                     precipLag1 = tempDataSyncS$prcpLagged1,
                     precipLag2 = tempDataSyncS$prcpLagged2) # , swe = tempDataSyncS$swe

data.random.years <- data.frame(intercept.year = 1, 
                     dOY = tempDataSyncS$dOY, 
                     dOY2 = tempDataSyncS$dOY^2,
                     dOY3 = tempDataSyncS$dOY^3)

monitor.params <- c("residuals",
            "deviance",
            "sigma",
            "B.0",
            "B.site",
            "rho.B.site",
            "mu.site",
            "sigma.b.site",
            "B.huc",
            "rho.B.huc",
            "mu.huc",
            "sigma.b.huc",
            "B.year",
            "rho.B.year",
            "mu.year",
            "sigma.b.year")

coda.tf <- T # currently only works in full for TRUE (using coda.samples)
system.time(M.huc <- modelRegionalTempHUC(tempDataSyncS, data.fixed=data.fixed, data.random.sites=data.random.sites, data.random.years=data.random.years, n.burn = 1000, n.it = 1000, n.thin = 1, nc = 3, coda = coda.tf, param.list = monitor.params))

save(M.huc, file = paste0(dataLocalDir, "northeast-mcmc.RData"))

#pdf("test-huc.pdf")
#plot(M.huc)
#dev.off()
```

## Evaluate MCMC Iterations
```{r check model convergence and mixing}
ggs.huc <- ggs(M.huc)
ggmcmc(ggs.huc, file = "ggmcmc-huc.pdf", family = "mu.huc", plot = c("ggs_density",  "ggs_traceplot", "ggs_running", "ggs_compare_partial", "ggs_autocorrelation", "ggs_crosscorrelation", "ggs_Rhat", "ggs_geweke", "ggs_caterpillar"))
dev.off()

ggs_traceplot(ggs.huc, family = "mu.huc")

huc.mat <- as.matrix(M.huc)
tempDataSyncS$resid.huc <- NA
for(i in 1:length(tempDataSyncS$temp)) {
  tempDataSyncS$resid.huc[i] <- mean(huc.mat[ , paste0("residuals[", i, "]")])
  #  tempDataSyncS$resid.huc[i] <- huc.mat[1 , paste0("residuals[", i, "]")]
  }
```

## Check model fit
```{r check model fit}
#------ Check residual patterns------
# Observed vs Residuals
g <- ggplot(tempDataSyncS, aes(temp, resid.ar1)) 
#g + geom_point(alpha = 0.3) + geom_smooth() + theme_bw()

library(hexbin)
g + stat_binhex(bins = 100) + geom_smooth() + theme_bw()

g + geom_point() + geom_density2d() + geom_smooth() + theme_bw()

# Residuals by random HUC8
b <- ggplot(tempDataSyncS, aes(x = HUC8, y = resid.ar1))
b + geom_boxplot() + coord_flip()

# Residuals by random site within HUC8
b <- ggplot(tempDataSyncS, aes(x = site, y = resid.ar1))
b + geom_boxplot() + coord_flip()

# Residuals by random year
ggplot(tempDataSyncS, aes(x = as.factor(year), y = resid.ar1)) + geom_boxplot() + coord_flip()

# Residuals by covariates
ggplot(tempDataSyncS, aes(Forest, resid.ar1)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()

ggplot(tempDataSyncS, aes(airTemp, resid.ar1)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()

ggplot(tempDataSyncS, aes(dOY, resid.ar1)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()

ggplot(tempDataSyncS, aes(dOY^2, resid.ar1)) + geom_point(alpha = 0.5) + geom_smooth() + theme_bw()

# Check Autocorrelation of residuals
# correlation in MCMC
acf(ar1.mat[ , "residuals[1]"], lag.max = 40, xlab = "Lag", ylab = "Correlation", main = "")
acf(ar1.mat[ , "residuals[2]"], lag.max = 40, xlab = "Lag", ylab = "Correlation", main = "")

# correlation in residuals over time 
acf(tempDataSyncS$resid.ar1, lag.max = 100, xlab = "Lag", ylab = "Correlation", main = "") # not perfect but better than for non-AR model

```

### Check model convergence
```{r convergence}
if(coda.tf) {
  pdf("/Users/Dan/Dropbox/correlatedSlopes.pdf")
  #pdf("C:/Users/dhocking/Dropbox/correlatedSlopes.pdf")
  plot(M3[ , 1:200])
  dev.off()
  
  pairs(as.matrix(M3[ , c(1:8, 17:20)]))
  
  mcmc.cor <- cor(as.matrix(M3))
  quantile(mcmc.cor, na.rm = TRUE, probs = c(0.5, 0.9, 0.99, 0.999. 0.9999))
  
  gelman.diag(M3[ , 1:99])
} else {
  ## deviance
#[1, 1:200, 3]
library(reshape2)
temp2 <- melt(((M3$deviance[,,])))
temp2 <- melt(((M3$sigma[,,])))
ggplot(temp2, aes(Var1,(value), colour=factor(Var2) )) +  
    geom_point(size=1) +
    scale_x_continuous('Iteration') +
    scale_y_continuous('Deviance') +
    ggtitle('desc')

## B.0
#[1:2, 1:200, 3]

temp2 <- melt(((M3$B.0[,,])))
temp2 <- melt(((M3$mu.year[,,])))
temp2 <- melt(((M3$mu.site[,,])))
temp2 <- melt(((M3$sigma.b.year[,,])))
temp2 <- melt(((M3$B.year[,,])))


ggplot(temp2, aes(Var2,(value), colour=factor(Var3) )) +  
    geom_point(size=1) +
    scale_x_continuous('Iteration') +
    scale_y_continuous('Deviance') +
    stat_smooth()+
    facet_grid(~Var1)


## B.Site
#[1:4, 1:4, 1:200, 3]

temp2 <- melt(((M3$B.site[,,,])))

ggplot(temp2[temp2$Var2==1,], aes(Var3,(value), colour=factor(Var4) )) +  
    geom_point(size=.25) +
    scale_x_continuous('Iteration') +
    scale_y_continuous('Deviance') +
    stat_smooth()+
    facet_wrap(Var2~Var1)
}

```

```{r ending info}

print(sessionInfo())

```





