---
title: "4-northeast-analysis"
author: "Daniel Hocking"
date: "August 28, 2014"
output: html_document
---

```{r}
rm(list=ls())

library(ggplot2)
library(dplyr)
library(nlme)
library(devtools)
#install_github("conteStreamTemperature", username = "Conte-Ecology")
library(conteStreamTemperature)

#setwd('/Users/Dan/Documents/Research/Stream_Climate_Change/temperatureProject/')
#setwd('C:/Users/dhocking/Documents/temperatureProject/')

#baseDir <- 'C:/KPONEIL/GitHub/projects/temperatureProject/'
#baseDir <- '/Users/Dan/Documents/Research/Stream_Climate_Change/temperatureProject/'
baseDir <- getwd() # works as long as you have the project loaded in RStudio

dataInDir <- paste0(baseDir, '/dataIn/')
dataOutDir <- paste0(baseDir, '/dataOut/')
dataLocalDir <- paste0(baseDir, '/localData/')
graphsDir <- paste0(baseDir, '/graphs/')

#source(paste0(baseDir, 'code/functions/temperatureModelingFunctions.R'))

loadLocalData <- F

if(loadLocalData) {
  load(paste0(dataLocalDir, 'etSCT'))
} else {
  load(paste0(dataOutDir, 'tempDataSync.RData'))
}


########## JAGS Model ##############

M3 <- modelRegionalTemp(tempDataSyncS, n.burn = 100, n.it = 100, n.thin = 3, n.chains = 3, coda = TRUE)

#pdf("/Users/Dan/Dropbox/correlatedSlopes.pdf")
pdf("C:/Users/dhocking/Dropbox/correlatedSlopes.pdf")
plot(M3[ , 1:50])
dev.off()

rm(out)

pairs(as.matrix(M3[ , c(1:8, 17:20)]))

memory.limit(size = 1e6)

summary.stats <- summary(M3)
summary.stats[1:1000, 1:2]

# Make "Fixed Effects" Output like summary(lmer)
#codaFixEf <- function (K.0, K, L, variables.fixed, variables.site, variables.year, k, summary.stats, l) {
  fix.ef <- as.data.frame(matrix(NA, K.0+K+L, 4))
  names(fix.ef) <- c("Mean", "Std. Error", "LCI", "UCI")
  row.names(fix.ef) <- c(variables.fixed, variables.site, variables.year)
  for(k in 1:K.0){
    fix.ef[k, 1:2] <- summary.stats$statistics[paste0('B.0[',k,']') , c("Mean", "SD")]
    fix.ef[k, 3:4] <- summary.stats$quantiles[paste0('B.0[',k,']') , c("2.5%", "97.5%")]
  }
  for(k in 1:K){
    fix.ef[k+K.0, 1:2] <- summary.stats$statistics[paste0('mu.site[',k,']') , c("Mean", "SD")]
    fix.ef[k+K.0, 3:4] <- summary.stats$quantiles[paste0('mu.site[',k,']') , c("2.5%", "97.5%")]
  }
  for(l in 1:L){
    fix.ef[l+K.0+K, 1:2] <- summary.stats$statistics[paste0('mu.year[',l,']') , c("Mean", "SD")]
    fix.ef[l+K.0+K, 3:4] <- summary.stats$quantiles[paste0('mu.year[',l,']') , c("2.5%", "97.5%")]
  }
#}
fix.ef

# Make Random Effects Output like summary(lmer)
ran.ef.site <- as.data.frame(matrix(NA, K, 2))
names(ran.ef.site) <- c("Variance", "SD")
row.names(ran.ef.site) <- variables.site
for(k in 1:K){
  ran.ef.site[k, 2] <- summary.stats$statistics[paste0('sigma.b.site[',k,']') , c("Mean")]
  ran.ef.site[k, 1] <- ran.ef.site[k, 2] ^ 2
}
ran.ef.site

S <- length(unique(tempDataSyncS$site))
B.site <- as.data.frame(matrix(NA, S, K))
names(B.site) <- variables.site
row.names(B.site) <- unique(tempDataSyncS$site)
for(s in 1:S){
  for(k in 1:K){
    B.site[s, k] <- summary.stats$statistics[paste('B.site[',s,',',k,']', sep=""), "Mean"]
  }
}

# Make Random Effects Output like summary(lmer)
ran.ef.year <- as.data.frame(matrix(NA, L, 2))
names(ran.ef.year) <- c("Variance", "SD")
row.names(ran.ef.year) <- variables.year
for(l in 1:L){
  ran.ef.year[l, 2] <- summary.stats$statistics[paste0('sigma.b.year[',l,']') , c("Mean")]
  ran.ef.year[l, 1] <- ran.ef.year[l, 2] ^ 2
}
ran.ef.year

Y <- length(unique(tempDataSyncS$year))
B.year <- as.data.frame(matrix(NA, Y, L))
names(B.year) <- variables.year
row.names(B.year) <- unique(tempDataSyncS$year)
for(y in 1:Y){
  for(l in 1:L){
    B.year[y, l] <- summary.stats$statistics[paste('B.year[',y,',',l,']', sep=""), "Mean"]
  }
}

# Make correlation matrix of random site effects
cor.site <- as.data.frame(matrix(NA, K, K))
names(cor.site) <- variables.site
row.names(cor.site) <- variables.site
for(k in 1:K){
  for(k.prime in 1:K){
    cor.site[k, k.prime] <- summary.stats$statistics[paste('rho.B.site[',k,',',k.prime,']', sep=""), "Mean"]
  }
}
cor.site <- round(cor.site, digits=3)
cor.site[upper.tri(cor.site, diag=TRUE)] <- ''
cor.site

# Make correlation matrix of random year effects
cor.year <- as.data.frame(matrix(NA, L, L))
names(cor.year) <- variables.year
row.names(cor.year) <- variables.year
for(l in 1:L){
  for(l.prime in 1:L){
    cor.year[l, l.prime] <- summary.stats$statistics[paste('rho.B.year[',l,',',l.prime,']', sep=""), "Mean"]
  }
}
cor.year <- round(cor.year, digits=3)
cor.year[upper.tri(cor.year, diag=TRUE)] <- ''
cor.year

# combine model summary results into an S4 Object
setClass("jagsSummary",
         representation(fixEf="data.frame",
                        ranEf="list",
                        ranCor="list",
                        BSite="data.frame",
                        BYear="data.frame"))

modSummary <- new("jagsSummary")
modSummary@fixEf <- fix.ef
modSummary@ranEf <- list(ranSite=ran.ef.site, ranYear=ran.ef.year)
modSummary@ranCor <- list(corSite=cor.site, corYear=cor.year)
modSummary@BSite <- B.site
modSummary@BYear <- B.year

# modSummary <- NULL
# modSummary$fixEf <- fix.ef
# modSummary$ranEf <- list(ranSite=ran.ef.site, ranYear=ran.ef.year)
# modSummary$ranCor <- list(corSite=cor.site, corYear=cor.year)
# modSummary$BSite <- B.site
# modSummary$BYear <- B.year

modSummary
str(modSummary)

modSummary
str(modSummary)

save(modSummary, file=paste0(dataOutDir, 'modSummary.RData'))
save(M3, file = paste0(dataOutDir, 'codaList-M3.RData'))
```

# Do not run below

# Add predicted stream temperatures to dataframe - will do this outside JAGS now
```{r}
tempDataSync$streamTempPred <- NA
tempDataSync$streamTempPredLCI <- NA
tempDataSync$streamTempPredUCI <- NA
for(i in 1:n){
  tempDataSync$streamTempPred[i] <- summary.stats$statistics[paste0('stream.mu[',i,']') , c("Mean")]
  tempDataSync$streamTempPredLCI[i] <- summary.stats$quantiles[paste0('stream.mu[',i,']') , c("2.5%")]
  tempDataSync$streamTempPredUCI[i] <- summary.stats$quantiles[paste0('stream.mu[',i,']') , c("97.5%")]
}


########## Check model fit #############
tempDataSync$err <- tempDataSync$streamTempPred - tempDataSync$temp
rmse(tempDataSync$err)
```

# Add fit for validation data
```{r}
########################################

############ Plots ###############
ggplot(tempDataSync, aes(temp, streamTempPred)) + geom_point() +geom_abline(slope=1, intercept=0, colour='red')

ggplot(tempDataSync, aes(airTemp, streamTempPred)) + geom_point(aes(colour = dOY, size=0.5, alpha=0.5)) + facet_grid(. ~ year)

ggplot(tempDataSync, aes(dOY, streamTempPred)) + geom_point(size=0.75) + geom_point(data=tempDataSync, aes(dOY, temp), colour = "red", size=0.75) + facet_grid(. ~ year)

ggplot(tempDataSync, aes(dOY, streamTempPred, colour = year)) + geom_line(size=0.5)


ggplot(tempDataSync, aes(dOY, streamTempPred, colour = year)) + geom_point(aes(group = year))

ggplot(tempDataSync, aes(airTemp, streamTempPred)) + geom_line(size = 0.5, alpha = 0.3) + theme_bw() + theme(legend.position="none")
ggplot(tempDataSync, aes(airTemp, streamTempPred, colour = site)) + geom_point(size = 0.5, alpha = 0.8) + theme_bw() + theme(legend.position="none")

ggplot(tempDataSync, aes(airTemp, streamTempPred, group = site)) + 
  geom_line(stat='smooth', method='lm', se=F, alpha=0.2, size=0.5, colour='black') + 
  theme_bw() +
  theme(legend.position="none") + 
  xlab('Air Temperature (C)') + 
  ylab('Predicted Stream Temperature (C)')

# plot observed and predicte vs day of the year for all sites
sites <- unique(tempDataSync$site)

for(i in 1:length(unique(tempDataSync$site))){
  dataSite <- filter(tempDataSync, filter = site == sites[i])
  foo <- ggplot(dataSite, aes(dOY, temp)) + coord_cartesian(xlim = c(50, 350), ylim = c(0, 30)) + geom_point(colour = 'blue') + geom_line(colour = 'blue') + geom_point(aes(dOY, streamTempPred), colour = 'red', size=1) + geom_line(aes(dOY, streamTempPred), colour = 'red', size=0.1) + geom_point(aes(dOY, airTemp), colour='black', size=1) + ggtitle(unique(tempDataSync$fsite)[i]) + facet_wrap(~year) + xlab(label = 'Day of the year') + ylab('Temperature (C)')
  ggsave(filename=paste0(dataLocalDir,'/', 'plots/', unique(tempDataSync$fsite)[i], '.png'), plot=foo, dpi=300 , width=6,height=4, units='in' )
} # surprisingly fast
```


###### Consider: Slope, Aspect, Dams/Impoundments, Agriculture, Wetland, Coarseness, dayl, srad, swe

###### Add correlation structure for Lat-Lon and/or HUC ########

##### Add autoregressive component to the model? #########

##### Add interactions such as airTemp*drainage






