# Do not run below

# Add predicted stream temperatures to dataframe - will do this outside JAGS now
```{r}
tempDataSync$streamTempPred <- NA
tempDataSync$streamTempPredLCI <- NA
tempDataSync$streamTempPredUCI <- NA
for(i in 1:n){
  tempDataSync$streamTempPred[i] <- summary.stats$statistics[paste0('stream.mu[',i,']') , c("Mean")]
  tempDataSync$streamTempPredLCI[i] <- summary.stats$quantiles[paste0('stream.mu[',i,']') , c("2.5%")]
  tempDataSync$streamTempPredUCI[i] <- summary.stats$quantiles[paste0('stream.mu[',i,']') , c("97.5%")]
}


########## Check model fit #############
tempDataSync$err <- tempDataSync$streamTempPred - tempDataSync$temp
rmse(tempDataSync$err)
```

# Add fit for validation data
```{r}
########################################

############ Plots ###############
ggplot(tempDataSync, aes(temp, streamTempPred)) + geom_point() +geom_abline(slope=1, intercept=0, colour='red')

ggplot(tempDataSync, aes(airTemp, streamTempPred)) + geom_point(aes(colour = dOY, size=0.5, alpha=0.5)) + facet_grid(. ~ year)

ggplot(tempDataSync, aes(dOY, streamTempPred)) + geom_point(size=0.75) + geom_point(data=tempDataSync, aes(dOY, temp), colour = "red", size=0.75) + facet_grid(. ~ year)

ggplot(tempDataSync, aes(dOY, streamTempPred, colour = year)) + geom_line(size=0.5)


ggplot(tempDataSync, aes(dOY, streamTempPred, colour = year)) + geom_point(aes(group = year))

ggplot(tempDataSync, aes(airTemp, streamTempPred)) + geom_line(size = 0.5, alpha = 0.3) + theme_bw() + theme(legend.position="none")
ggplot(tempDataSync, aes(airTemp, streamTempPred, colour = site)) + geom_point(size = 0.5, alpha = 0.8) + theme_bw() + theme(legend.position="none")

ggplot(tempDataSync, aes(airTemp, streamTempPred, group = site)) + 
  geom_line(stat='smooth', method='lm', se=F, alpha=0.2, size=0.5, colour='black') + 
  theme_bw() +
  theme(legend.position="none") + 
  xlab('Air Temperature (C)') + 
  ylab('Predicted Stream Temperature (C)')

# plot observed and predicte vs day of the year for all sites
sites <- unique(tempDataSync$site)

for(i in 1:length(unique(tempDataSync$site))){
  dataSite <- filter(tempDataSync, filter = site == sites[i])
  foo <- ggplot(dataSite, aes(dOY, temp)) + coord_cartesian(xlim = c(50, 350), ylim = c(0, 30)) + geom_point(colour = 'blue') + geom_line(colour = 'blue') + geom_point(aes(dOY, streamTempPred), colour = 'red', size=1) + geom_line(aes(dOY, streamTempPred), colour = 'red', size=0.1) + geom_point(aes(dOY, airTemp), colour='black', size=1) + ggtitle(unique(tempDataSync$fsite)[i]) + facet_wrap(~year) + xlab(label = 'Day of the year') + ylab('Temperature (C)')
  ggsave(filename=paste0(dataLocalDir,'/', 'plots/', unique(tempDataSync$fsite)[i], '.png'), plot=foo, dpi=300 , width=6,height=4, units='in' )
} # surprisingly fast
```

